const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db');
const User = require('./User');
const { generateSecret } = require('../utils/totp');

const TrustedContact = sequelize.define('TrustedContact', {
    id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true,
    },
    userId: {
        type: DataTypes.UUID,
        allowNull: false,
        references: {
            model: User,
            key: 'id'
        }
    },
    contactName: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
            notNull: { msg: 'Please add a contact name' },
            notEmpty: { msg: 'Please add a contact name' }
        }
    },
    contactPhone: {
        type: DataTypes.STRING(20),
        allowNull: false,
        validate: {
            notNull: { msg: 'Please add a contact phone number' },
            notEmpty: { msg: 'Please add a contact phone number' }
        }
    },
    contactEmail: {
        type: DataTypes.STRING,
        allowNull: true,
        validate: {
            isEmail: { msg: 'Please add a valid email' }
        }
    },
    relationship: {
        type: DataTypes.STRING(100),
        allowNull: true
    },
    isVerified: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false
    },
    accessCode: {
        // Stable, non-secret contact handle (e.g. "SC-A3F2B1C9").
        // Shared once in the invitation message so the trusted contact can
        // identify WHICH secret to use when requesting a TOTP verification.
        // This is NOT the authentication factor — the rotating TOTP token is.
        type: DataTypes.STRING(20),
        allowNull: true,
        unique: true
    },
    totpSecret: {
        // RFC 6238 TOTP base32 secret — stored server-side only, never sent
        // to the client. Used to validate 6-digit tokens generated by an
        // authenticator app (Google Authenticator, Authy, etc.).
        type: DataTypes.STRING(64),
        allowNull: true
    },
    sharingMode: {
        type: DataTypes.STRING(20),
        allowNull: false,
        defaultValue: 'EMERGENCY_ONLY'
    }
}, {
    timestamps: true,
    hooks: {
        beforeCreate: async (contact) => {
            // FIX: Replace Math.random() static code with proper RFC 6238 TOTP.
            //
            // accessCode  — stable 8-char hex handle derived from 4 crypto-random
            //               bytes. Shared once in the invitation; identifies WHICH
            //               contact relationship to look up. Not a secret.
            //
            // totpSecret  — base32-encoded cryptographic TOTP secret generated by
            //               otplib. Never shared directly. The contact adds the
            //               provisioning URI to Google Authenticator / Authy and
            //               receives rotating 6-digit tokens every 30 seconds.
            const randomBytes = require('crypto').randomBytes(4);
            contact.accessCode = 'SC-' + randomBytes.toString('hex').toUpperCase();
            contact.totpSecret = generateSecret();
        }
    }
});

// Setup relationships
User.hasMany(TrustedContact, { foreignKey: 'userId', as: 'trustedContacts' });
TrustedContact.belongsTo(User, { foreignKey: 'userId', as: 'user' });

module.exports = TrustedContact;
